application: new-project-template
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*)static(.*)
  static_files: web/\1static\2
  upload: web/.*static.*

- url: /
  script: convention.app

- url: /([^_]).*
  script: convention.app
